version: '3.7'

services:

  git-server:
    image: anarkrypto/git-server-docker
    build:
      context: . # Build Dockerfile from current directory
    restart: unless-stopped
    container_name: git-server
    image: anarkrypto/git-server-docker
    ports:
      - "2222:22"
    volumes:
    - ~/git-server/keys:/git-server/keys
    - ~/git-server/repos:/git-server/repos

